version: '3.9'

services:
  car_sales-postgres:
    image: postgis/postgis
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: car_sales
    volumes:
      - car_sales-db:/var/lib/postgresql/car_sales

volumes:
  car_sales-db: